version: '3.5'

services:
  starterkitdb:
    image: 'postgres-starterkit'
    volumes:
      - ./pg_data:/dbdata/postgres
    expose:
      - '5432'
    ports:
      - "5432:5432"
    networks:
      - default
