apiVersion: v1
kind: Service
metadata:
  name: app_name_here
  labels:
    app: app_name_here
spec:
  type: NodePort
  ports:
  - port: 3010
    nodePort: 30300
    protocol: TCP
  selector:
    app: app_name_here
